# quant-econ Solutions: Markov Asset Pricing

Solutions for http://quant-econ.net/py/markov_asset.html

In [1]:
import numpy as np
import quantecon as qe

Next we load the code from the lectures into a cell to have access to the functions.  This next line assumes that you have the file `asset_pricing.py` from [QuantEcon.applications](https://github.com/QuantEcon/QuantEcon.applications) in the same directory as this notebook.

In [8]:
from asset_pricing import *

## Exercise 1

First let's enter the parameters:

In [9]:
# parameters for object
n = 5
P = 0.0125 * np.ones((n, n))
P += np.diag(0.95 - 0.0125 * np.ones(5))
s = np.array([1.05, 1.025, 1.0, 0.975, 0.95])  # state values
mc = qe.MarkovChain(P, state_values=s)

gamma = 2.0
beta = 0.94
zeta = 1.0
p_s = 150.0

Next we'll create an instance of `AssetPriceModel` to feed into the functions.

In [10]:
apm = AssetPriceModel(beta, mc, gamma)

Now we just need to call the relevent functions on the data:

In [11]:
tree_price(apm)

array([ 12.72221763,  14.72515002,  17.57142236,  21.93570661,  29.47401578])

In [12]:
consol_price(apm, zeta)

array([  87.56860139,  109.25108965,  148.67554548,  242.55144082,
        753.87100476])

In [13]:
call_option(apm, zeta, p_s)

(array([  64.30843769,   80.05179282,  108.67734545,  176.83933585,
         603.87100476]), {})